FROM amd64/golang:1.17.13
# Set the working directory to /tmp
WORKDIR /tmp

#RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o main .

# Install the beego and bee packages
RUN go get github.com/beego/beego
RUN go get github.com/beego/bee

# Install the mgo and jwt-go packages
RUN go get gopkg.in/mgo.v2/bson
RUN go get github.com/dgrijalva/jwt-go

# Install the redigo package
RUN go get github.com/garyburd/redigo/redis

# Set the working directory to /
WORKDIR /
